# Configuration for McNotify - https://github.com/kivy/mcnotify

subscriptions:
  - events:
      # Events which trigger notifications
      labeled: api-break
    # Issue used for posting notifications
    issue: 5560
    # Comment to post on the notification thread. Optional placeholders: {label},
    # {issue-author}, {issue-title} and {issue-url}
    comment: >
      @{issue-author} proposed the following change: "{issue-title}".
      Please follow the changes or comment at {issue-url}.
