version = 1

test_patterns = ["kivy/tests/**/test_*.py"]

exclude_patterns = [
    "doc/**",
    "examples/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
