#!/usr/bin/env python
# encoding: utf-8
'''
pyxversions -- interpreter listing

pyxversions is a tool listing all python interpreters found in PATH.

@author:     Thomas-Karl Pietrowski

@copyright:  2014 openBergisch. All rights reserved.

@license:    GPLv3

@contact:    thopiekar@googlemail.com
@deffield    updated: 10.04.2014
'''

import os
import argparse

if not ("PATH" in os.environ.keys() and os.name is "posix"):
    print "We only support a posix system owning a PATH environment variable!"

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('--major_version', dest='major_version', default=3,
                    help='major version of the python interpreters to be listed (default: 3)')
parser.add_argument('--min_minor', dest='min_minor', default=0, type=int,
                    help='minimum minor version of the python interpreters to be listed (default: 0)')
args = parser.parse_args()
keyword = "python%s" %(args.major_version)

interpreters = []
for path in os.environ["PATH"].split(":"):
    if os.path.isdir(path):
        for executable in os.listdir(path):
            if keyword in executable[:len(keyword)] and len(executable[len(keyword)-1:]) is 3: # expecting version appended as 'x.y'
                if int(executable[len(keyword)-1:].split(".")[1]) >= args.min_minor:
                    interpreters.append(executable)

print(' '.join(interpreters))
