/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__kivy__graphics__cgl
#define __PYX_HAVE__kivy__graphics__cgl

#include "Python.h"

#ifndef __PYX_HAVE_API__kivy__graphics__cgl

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int verify_gl_main_thread;

#endif /* !__PYX_HAVE_API__kivy__graphics__cgl */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcgl(void);
#else
PyMODINIT_FUNC PyInit_cgl(void);
#endif

#endif /* !__PYX_HAVE__kivy__graphics__cgl */
