User's Guide
------------

This part of the documentation explains the basic ideas behind Kivy's design
and why you'd want to use it.
It goes on with a discussion of the architecture and shows you how to create
stunning applications in short time using the framework.

.. toctree::
    :maxdepth: 2

    philosophy.rst
    faq.rst
    guide-index.rst
    architecture.rst
    contribute.rst


API Reference
-------------

The API reference is a lexicographic list of all the different classes,
methods and features that Kivy offers.

.. toctree::
    :maxdepth: 4

    api-index.rst
