User's Guide
------------

This part of the documentation explains the basic ideas behind Kivy's design
and why you'd want to use it.
It goes on with a discussion of the architecture and shows you how to create
stunning applications in short time using the framework.

.. toctree::
    :maxdepth: 2

    philosophy
    installation/installation
    guide-index
    tutorials-index
    contribute
    faq
    contact


.. include:: api-index.rst
