#:kivy 1.4

BoxLayout:
    # Double as a Tabbed Panel Demo!
    TabbedPanel:
        tab_pos: "top_right"
        default_tab_text: "List View"
        default_tab_content: list_view_tab

        TabbedPanelHeader:
            text: 'Icon View'
            content: icon_view_tab

        FileChooserListView:
            id: list_view_tab

        FileChooserIconView:
            id: icon_view_tab
            show_hidden: True
