PageLayout:
    FloatLayout:
        canvas:
            Color:
                rgba:205.0/255,220.0/255,57.0/255,1
            Rectangle:
                pos:self.pos
                size:self.size
        Label:
            text:"This is Float layout!!" 
        Label:
            text:"This is Float layout!!"
            size_hint:.5,.5
        
            


    AnchorLayout:
        canvas:
            Color:
                rgba:255.0/255,152.0/255,0.0,1
            Rectangle:
                pos:self.pos
                size:self.size
        anchor_x: 'left'
        anchor_y: 'top'
        Label:
            size_hint:.4,.4
            text:"This is anchor layout,(top,left)!!"           
    
    
    
    BoxLayout: 
        canvas:
            Color:
                rgba:96.0/255,125.0/255,139.0/255,1
            Rectangle:
                pos:self.pos
                size:self.size
        Label:
            text:"Horizontal B.L!!"
        Label:
            text:"Horizontal B.L!!"
        Label:
            text:"Horizontal B.L!!"
        Label:
            text:"Horizontal B.L!!"
    
    BoxLayout:
        orientation:'vertical' 
        canvas:
            Color:
                rgba:96.0/255,125.0/255,139.0/255,1
            Rectangle:
                pos:self.pos
                size:self.size
        Label:
            text:"Vertical box layout!!"
        Label:
            text:"Vertical box layout!!"
        Label:
            text:"Vertical box layout!!"
        Label:
            text:"Vertical box layout!!"
    
    GridLayout:
        canvas:
            Color:
                rgba:76.0/255,175.0/255,80.0/255,1
            Rectangle:
                pos:self.pos
                size:self.size
        cols:2
        Label:
            text:"Grid layout!!"
        Label:
            text:"Grid layout!!"
        Label:
            text:"Grid layout!!"
        Label:
            text:"Grid layout!!"
        Label:
            text:"Grid layout!!"
        Label:
            text:"Grid layout!!" 
    
    
    RelativeLayout:
        canvas:
            Color:
                rgba:139.0/255,195.0/255,74.0/255,1
            Rectangle:
                pos:self.pos
                size:self.size
        Label:
            text:"This is Relative layout!!"
    
    
    BoxLayout:
        canvas:
            Color:
                rgba:205.0/255,220.0/255,57.0/255,1
            Rectangle:
                pos:self.pos
                size:self.size
        ScatterLayout:
            Label:
                text:"This is Scatter Layout!! move me around!"
    
    
    StackLayout:
        canvas:
            Color:
                rgba:255.0/255,193.0/255,7.0/255,1
            Rectangle:
                pos:self.pos
                size:self.size
        Button:
            text:"Stack Layout(1)!!"
            size_hint:0.2,0.2
        Button:
            text:"Stack Layout(2)!!"
            size_hint:0.2,0.2
        Button:
            text:"Stack Layout(3)!!"
            size_hint:0.30,0.30
        Button:
            text:"SL(4)!!"
            size_hint:0.1,0.2
        Button:
            text:"SL(5)!!"
            size_hint:0.1,0.09
        Button:
            text:"Stack Layout is awesome!!Kivy too"
            size_hint:0.4,.3
        Button:
            text:"SL(6)"
            size_hint:0.08,0.08
 
