Camera:
	canvas:
		Color:
			rgb: (1, 1, 1)
		Rectangle:
			texture: self.texture
			size: (320, 240)
		Color:
			rgb: (.5, 0, 1)
		Rectangle:
			texture: self.texture
			pos: (320, 0)
			size: (320, 240)
		Color:
			rgb: (0, 1, 0)
		Rectangle:
			texture: self.texture
			pos: (320, 240)
			size: (320, 240)
		Color:
			rgb: (1, 0, 0)
		Rectangle:
			texture: self.texture
			pos: (0, 240)
			size: (320, 240)
